### ISSUE TITLE
`manifest.json` treated as a random obscure schema (Foxx) instead of web extension

### ISSUE THREAD

**Issue by zopieux** [remcohaszing/vscode-schemastore#2]
As title said, `manifest.json` file is treated as `foxx-manifest.json` schema, but it's a web extension manifest. How does one override the file schema when the extension decides to use the incorrect one based on filename alone?

**Comment by remcohaszing** [comment]
Users can’t select a schema, and neither can this extension, which consists really just of a generated static extension manifest. This is generated using the [`build.js`](https://github.com/remcohaszing/vscode-schemastore/blob/main/build.js) script.

Some entries matches accept multiple versions of a schema. For such cases, an `anyOf` schema is written to the [`schemas`](https://github.com/remcohaszing/vscode-schemastore/tree/main/schemas). This schema references all allowed schemas. The same needs to happen for conflicting file matches.

Would you like to provide a PR for this?

**Comment by zopieux** [comment]
I sadly do not have prior VS extension experience, and won't be able to invest the time.

By the way, if anyone ends up doing this, the UX would need some care. I'd argue VS settings are *not* the right place for storing such an override – the association should most likely be stored in VCS (gitattributes? yet another repo dotfile?) instead, to benefit all users.

**Comment by remcohaszing** [comment]
It will be updated and released tonight by a scheduled GitHub action.

**Comment by zopieux** [comment]
Awesome thanks.
