### ISSUE TITLE
Schema collides with `.vscode/settings.json` schema

### ISSUE THREAD

**Issue by ITProKyle** [remcohaszing/vscode-schemastore#3]
After a recent update of this extension, the following schema overlaps with the schema for `.vscode/settings.json` (and the user `settings.json` file) resulting in `Property ... is not allowed` warning in these files.

https://github.com/remcohaszing/vscode-schemastore/blob/d5b3f3c1c22278bfac0af55998e423e65d40af5b/package.json#L851-L854

This has been patched in https://github.com/SchemaStore/schemastore/pull/3719. Can this extensions update please be triggered before it's scheduled time?

Feel free to close this as soon as v1.0.143 is released, either via manual trigger or schedule.

Thanks!

**Comment by remcohaszing** [comment]
Version 1.0.143 has already been published. Next time you have problems with a VSCode extension (any extension, not just this one), know that you can install an older version :)
